### ISSUE TITLE
camera pose file for the real cactus data

### ISSUE THREAD

**Issue by DevikalyanDas** [ecmjohnson/ub4d#2]
Hello Erik, Thanks for your excellent work ! I found that you are obtaining the camera pose from the .npy file in the shape of 3x5 where the the fifth column has height, width and focus which will be essential for camera intrinsics.  I wanted the correct Rotation and Translation matrices. How to get that from this file (.npy)?  Thank You

**Comment by ecmjohnson** [comment]
I hope our data/code can help you! For the real-world scenes (including RealCactus), we used the [LLFF](https://github.com/Fyusion/LLFF) data format which is read by [this file](https://github.com/ecmjohnson/ub4d/blob/main/utils/load_llff.py). Note that the poses arrays are further processed [here](https://github.com/ecmjohnson/ub4d/blob/main/utils/load_llff.py#L261) after the call to [`_load_data`](https://github.com/ecmjohnson/ub4d/blob/main/utils/load_llff.py#L63). The camera matrix is essentially computed from the 3x4 matrix left after stripping the last column of the 3x5 matrix containing the height, width, and focus. Note that the axis conventions you use may differ from those used in Ub4D and that would affect how you process the data loaded from `poses_bounds.npy`.

I would recommend that you visualize the cameras after loading the 3x4 matrices (e.g. after the call to `load_llff_data` [here](https://github.com/ecmjohnson/ub4d/blob/main/utils/dataset.py#L72)): the last column is the position and the 3x3 matrix is the orientation of the camera. Visualizing them should give you the understanding necessary to then adapt to your axis conventions. Feel free to reuse the [`load_llff.py`](https://github.com/ecmjohnson/ub4d/blob/main/utils/load_llff.py) file if that can help.
